name: ShiftToFix
version: 2.0
main: rx5600xt.sxqe.shifttofix.ShiftToFix
description: A plugin to enhance shift-click behavior
api-version: '1.13'
author: RX_5600XT

commands:
  stfset:
    description: Set the amount of durability increase
    usage: /stfset <amount>
    permission: shifttofix.setdurability

  stf:
    description: Help command
    usage: /stf
    permission: stf.help

  stfreload:
    description: Reload the plugin configuration
    usage: /stfreload
    permission: shifttofix.reload

  stfon:
    description: Enable ShiftToFix plugin functionality
    usage: /stfon
    permission: shifttofix.toggle

  stfoff:
    description: Disable ShiftToFix plugin functionality
    usage: /stfoff
    permission: shifttofix.toggle
